version: '3.8'
services:
  stive-api:
    build:
        context: .
    container_name: stive_container
    restart: always
    ports:
      - "3312:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
